vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/uploads/images'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
